name: the-team-assignment-team-27 file organizer 

on:                                                     
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Required Tools
        run: sudo apt-get update && sudo apt-get install -y coreutils

      - name: Create testing files for duplicate_delete.sh
        run: |
          mkdir -p testing
          echo "This is a test for duplicate_deleting.sh" > testing/test1.txt
          echo "This is a test for duplicate_deleting.sh" > testing/test2.txt
          echo "This is a test for duplicate_deleting.sh" > testing/test3.txt
          echo "preliminaryPlanning.txt" > ./backupFiles.txt

      - name: Make script executable
        run: |
          chmod 755 test_script.sh
          chmod +x backup2.sh

      - name: Run Tests
        run: ./test_script.sh > test_results.txt

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt
          
      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -f testing/test1.txt duplicates.txt
          rm -rf testing
