name: the-team-assignment-team-27 file organizer 

on:                                                     
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Test Environment for backup script
        run: mkdir BACKUP

      - name: Run Tests
        run: ./test_script.sh > test_results.txt

      - name: Upload Test Results
        if: ${{ always() }}

        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt